"""Mechanical checks on an example sentence, before anyone believes it.

An AI-written example gets the same distrust an AI-read vocabulary table gets
(DESIGN_V2, "Mechanical QC"). These are the checks a machine can settle without
asking anyone, so that a human review is spent on the things only a human can
judge:

* **Does the sentence actually use the word?** A model asked for an example of
  話す sometimes returns a fine sentence about 言う. The target may appear
  conjugated, so the test is against the code-generated forms from
  :mod:`conjugation` — rules over the expression, not a second guess.
* **Is the furigana the dictionary's, or the model's?** Segmentation is exactly
  what a model invents plausibly and wrongly, and this furigana goes on to
  drive sentence audio. It is checked against jpdb's own parse of the sentence.
* **Is the romaji derived from that furigana?** Model-supplied romaji is
  discarded outright and regenerated by :mod:`romaji`, because romaji is a
  mechanical transliteration and there is no reason to accept a guess at one.

Pure functions, no CLI and no network: the caller supplies the parse.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, replace

from japanese_anki import jpdb
from japanese_anki.conjugation import conjugate
from japanese_anki.models import ExampleSentence
from japanese_anki.romaji import kana_to_romaji

__all__ = [
    "FuriganaVerdict",
    "example_contains_target",
    "furigana_pairs",
    "furigana_reading",
    "parse_pairs",
    "regenerate_example_romaji",
    "target_forms",
    "verify_example_furigana",
]

# One bracketed group in Anki furigana notation: the run of characters before
# ``[``, up to a space, and the reading inside the brackets. The space is what
# separates a ruby group from kana in front of it, which is why it terminates
# the text run.
_GROUP = re.compile(r"([^\s\[\]]+)\[([^\[\]]+)\]")


def target_forms(expression: str, verb_group: str = "") -> tuple[str, ...]:
    """Every written form the target may legitimately appear as.

    The dictionary form plus whatever :func:`conjugation.conjugate` derives for
    its class — 話す also shows up as 話した, 話して, 話さない. A word janki has
    no verb class for contributes only its dictionary form, which is the right
    answer rather than a guess: an unconjugatable word simply has to appear as
    written.

    Longest first, so a caller reporting *which* form matched names 話さなかった
    rather than the 話 inside it.
    """
    expression = expression.strip()
    if not expression:
        return ()
    forms = {expression}
    forms.update(
        form for form in conjugate(expression, "", verb_group).values() if form
    )
    return tuple(sorted(forms, key=lambda form: (-len(form), form)))


def example_contains_target(
    example: ExampleSentence, expression: str, verb_group: str = ""
) -> bool:
    """Does this example actually use the word it is an example of?

    Checked against the plain sentence rather than the furigana, because the
    furigana carries bracketed readings that would match text no reader sees.
    An example that fails this is rejected outright: it may be a perfectly good
    sentence, but it is not an example of *this* word, and a card whose sentence
    does not contain its own headword teaches the wrong association.
    """
    sentence = example.japanese
    if not sentence.strip():
        return False
    return any(form in sentence for form in target_forms(expression, verb_group))


def furigana_pairs(furigana: str) -> tuple[tuple[str, str], ...]:
    """The ``(text, reading)`` groups in Anki furigana notation, in order."""
    return tuple((match.group(1), match.group(2)) for match in _GROUP.finditer(furigana))


def parse_pairs(parse: jpdb.ParseResult) -> tuple[tuple[str, str], ...]:
    """The ``(text, reading)`` groups jpdb's parse of a sentence states."""
    pairs: list[tuple[str, str]] = []
    for token in parse.tokens:
        for segment in _segments(token.get("furigana")):
            if isinstance(segment, str):
                continue
            if len(segment) == 2 and all(isinstance(part, str) for part in segment):
                pairs.append((segment[0], segment[1]))
    return tuple(pairs)


def _segments(value: object) -> list[object]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, list | tuple):
        return list(value)
    return []


def furigana_reading(furigana: str) -> str:
    """The kana a whole sentence's Anki furigana spells out.

    Bracketed groups contribute their reading, everything else contributes
    itself — so ``話[はな]すを 食[た]べる`` reads ``はなすをたべる``. The spaces
    Anki needs before a ruby group are notation, not sound, and are dropped.
    """
    out: list[str] = []
    position = 0
    for match in _GROUP.finditer(furigana):
        out.append(furigana[position : match.start()])
        out.append(match.group(2))
        position = match.end()
    out.append(furigana[position:])
    return "".join(out).replace(" ", "").replace("　", "")


@dataclass(frozen=True, slots=True)
class FuriganaVerdict:
    """Whether an example's furigana is the dictionary's or the model's.

    ``expected`` and ``found`` are both rendered so a human reading a warning
    can see the whole sentence rather than a list of pairs.
    """

    verified: bool
    expected: str
    found: str
    differences: tuple[str, ...] = ()

    def __bool__(self) -> bool:
        return self.verified


def verify_example_furigana(
    example: ExampleSentence, parse: jpdb.ParseResult
) -> FuriganaVerdict:
    """Check an example's furigana against jpdb's parse of the same sentence.

    The verdict is on the **readings assigned to each kanji run**, in order —
    not on the rendered string. jpdb does not tokenize punctuation, so
    comparing renderings would report a mismatch for a full stop.

    A missing space *does* fail, and should: ``お茶[ちゃ]`` puts ちゃ over both
    characters rather than over 茶, so Anki renders the wrong ruby and
    :func:`furigana_reading` yields ``ちゃ`` — the お is simply gone, and that
    truncated reading is what sentence audio would speak. The space is
    notation, but it is notation that decides which characters a reading
    belongs to.

    A sentence with no kanji has no groups on either side, and verifies.
    """
    expected_pairs = parse_pairs(parse)
    found_pairs = furigana_pairs(example.furigana)
    expected = jpdb.furigana_to_anki(
        [segment for token in parse.tokens for segment in _segments(token.get("furigana"))]
    )

    if expected_pairs == found_pairs:
        return FuriganaVerdict(True, expected, example.furigana)

    differences: list[str] = []
    for index in range(max(len(expected_pairs), len(found_pairs))):
        theirs = expected_pairs[index] if index < len(expected_pairs) else None
        ours = found_pairs[index] if index < len(found_pairs) else None
        if theirs == ours:
            continue
        if theirs is None:
            differences.append(f"{ours[0]}[{ours[1]}] is not in jpdb's reading")
        elif ours is None:
            differences.append(f"jpdb reads {theirs[0]} as {theirs[1]}; nothing here")
        elif theirs[0] != ours[0]:
            differences.append(
                f"jpdb splits {theirs[0]} where this splits {ours[0]}"
            )
        else:
            differences.append(f"jpdb reads {theirs[0]} as {theirs[1]}, not {ours[1]}")
    return FuriganaVerdict(False, expected, example.furigana, tuple(differences))


def regenerate_example_romaji(example: ExampleSentence) -> ExampleSentence:
    """The example with its romaji rebuilt from its furigana.

    Whatever romaji the example arrived with is discarded rather than checked.
    Romaji is a mechanical transliteration of a reading janki already has, so
    there is nothing a model could contribute but an opportunity to be wrong —
    and a wrong romaji is invisible to a learner who is reading it *because*
    they cannot yet read the kana.

    A sentence with no furigana is romanized from its own text, which is right
    when it holds no kanji and refuses to guess when it does: transliterating
    kanji is exactly the invention this function exists to remove.
    """
    reading = furigana_reading(example.furigana) if example.furigana else example.japanese
    return replace(example, romaji=kana_to_romaji(reading) if reading else "")
