"""Mechanical checks on an example sentence, before anyone believes it.

An AI-written example gets the same distrust an AI-read vocabulary table gets
(DESIGN_V2, "Mechanical QC"). These are the checks a machine can settle without
asking anyone, so that a human review is spent on the things only a human can
judge:

* **Does the sentence actually use the word?** A model asked for an example of
  話す sometimes returns a fine sentence about 言う. The target may appear
  conjugated, so the test is against the code-generated forms from
  :mod:`conjugation` — rules over the expression, not a second guess.
* **Is the furigana the dictionary's, or the model's?** Segmentation is exactly
  what a model invents plausibly and wrongly, and this furigana goes on to
  drive sentence audio. It is checked against jpdb's own parse of the sentence.
* **Is the romaji derived from that furigana?** Model-supplied romaji is
  discarded outright and regenerated by :mod:`romaji`, because romaji is a
  mechanical transliteration and there is no reason to accept a guess at one.

Pure functions, no CLI and no network: the caller supplies the parse.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, replace

from japanese_anki import jpdb
from japanese_anki.conjugation import conjugate
from japanese_anki.identifiers import normalize_identity_part
from japanese_anki.models import ExampleSentence
from japanese_anki.romaji import kana_to_romaji

__all__ = [
    "FuriganaVerdict",
    "example_contains_target",
    "furigana_base",
    "furigana_pairs",
    "furigana_reading",
    "parse_pairs",
    "regenerate_example_romaji",
    "target_forms",
    "token_text",
    "verify_example_furigana",
]

# One bracketed group in Anki furigana notation: the run of characters before
# ``[``, up to a space, and the reading inside the brackets. The space is what
# separates a ruby group from kana in front of it, which is why it terminates
# the text run.
#
# **The ASCII space, and only that.** Anki's own furigana filter separates on
# it alone, so a full-width space — ordinary in Japanese text, and what a model
# may well write — does not end the run there either. Treating it as a
# separator here would verify ``お　茶[ちゃ]`` while Anki renders ちゃ over both
# characters: the same wrong-ruby, truncated-audio failure a missing space
# causes, arriving through a different character.
_GROUP = re.compile(r"([^ \[\]]+)\[([^\[\]]+)\]")


def target_forms(expression: str, verb_group: str = "") -> tuple[str, ...]:
    """Every written form the target may legitimately appear as.

    The dictionary form plus whatever :func:`conjugation.conjugate` derives for
    its class — 話す also shows up as 話した, 話して, 話さない. A word janki has
    no verb class for contributes only its dictionary form, which is the right
    answer rather than a guess: an unconjugatable word simply has to appear as
    written.

    Longest first, so a caller reporting *which* form matched names 話さなかった
    rather than the 話 inside it.
    """
    # Normalized like the sentence it will be searched in. `conjugate`
    # normalizes internally, so the derived forms were already composed — but a
    # word with no verb class contributes only this one, which is most
    # vocabulary, and a decomposed headword would match nothing.
    expression = normalize_identity_part(expression)
    if not expression:
        return ()
    forms = {expression}
    forms.update(
        form for form in conjugate(expression, "", verb_group).values() if form
    )
    return tuple(sorted(forms, key=lambda form: (-len(form), form)))


def example_contains_target(
    example: ExampleSentence, expression: str, verb_group: str = ""
) -> bool:
    """Does this example actually use the word it is an example of?

    Checked against the plain sentence rather than the furigana, because the
    furigana carries bracketed readings that would match text no reader sees.
    An example that fails this is rejected outright: it may be a perfectly good
    sentence, but it is not an example of *this* word, and a card whose sentence
    does not contain its own headword teaches the wrong association.
    """
    # Normalized on both sides: `conjugate` returns NFKC forms, while an
    # example's text is only stripped, so a sentence carrying a decomposed
    # dakuten (食べた as た + U+3099 — the combining characters this project's
    # inputs are documented to contain) would never match a composed form. A
    # failed check rejects the example outright, so that miss is a silent drop
    # of a good sentence.
    sentence = normalize_identity_part(example.japanese)
    if not sentence.strip():
        return False
    return any(form in sentence for form in target_forms(expression, verb_group))


def furigana_pairs(furigana: str) -> tuple[tuple[str, str], ...]:
    """The ``(text, reading)`` groups in Anki furigana notation, in order.

    Normalized, like everything else these are compared against: a reading
    written with a decomposed dakuten would otherwise fail against jpdb's
    composed one and report ``jpdb reads 語 as ご, not ご`` — two strings that
    render identically, so the rejection cannot be diagnosed at all.
    """
    return tuple(
        (normalize_identity_part(match.group(1)), normalize_identity_part(match.group(2)))
        for match in _GROUP.finditer(furigana)
    )


def parse_pairs(parse: jpdb.ParseResult) -> tuple[tuple[str, str], ...]:
    """The ``(text, reading)`` groups jpdb's parse of a sentence states."""
    pairs: list[tuple[str, str]] = []
    for token in parse.tokens:
        for segment in _segments(token.get("furigana")):
            if isinstance(segment, str):
                continue
            if len(segment) == 2 and all(isinstance(part, str) for part in segment):
                text, reading = segment
                # The same collapse `jpdb.furigana_to_anki` applies when it
                # writes these fields: a segment that reads as itself carries
                # no ruby, so it is not a group. Without this, furigana janki
                # rendered from a parse could fail verification against that
                # very parse.
                text = normalize_identity_part(text)
                reading = normalize_identity_part(reading)
                if not reading or reading == text:
                    continue
                pairs.append((text, reading))
    return tuple(pairs)


def _segments(value: object) -> list[object]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, list | tuple):
        return list(value)
    return []


def furigana_base(furigana: str) -> str:
    """The sentence a furigana field spells, with every reading removed.

    ``話[はな]すを 食[た]べる`` bases to ``話すを食べる``. This is what the
    furigana claims the sentence *is*, and comparing it with the example's own
    text is what stops a model rewriting the sentence inside the furigana
    field.
    """
    out: list[str] = []
    position = 0
    for match in _GROUP.finditer(furigana):
        out.append(furigana[position : match.start()])
        out.append(match.group(1))
        position = match.end()
    out.append(furigana[position:])
    return "".join(out).replace(" ", "").replace("\u3000", "")


def token_text(parse: jpdb.ParseResult, token: dict) -> str:
    """The written text of one token, furigana or not.

    jpdb sends ``furigana: null`` for an all-kana token — を, と, たべる in the
    committed capture are all null — so a rendering built from furigana alone
    silently drops whole words. The text comes off the dictionary entry the
    token resolves to instead, which is the entry's *dictionary* form: a
    conjugated kana token shows as たべる where the sentence said たべた. That
    is accurate about what jpdb matched, and this text is only ever shown to a
    human beside the sentence itself.
    """
    segments = _segments(token.get("furigana"))
    if segments:
        return "".join(
            segment if isinstance(segment, str) else str(segment[0])
            for segment in segments
        )
    entry = parse.vocabulary_for(token)
    return str(entry.get("spelling") or "") if entry else ""


def furigana_reading(furigana: str) -> str:
    """The kana a whole sentence's Anki furigana spells out.

    Bracketed groups contribute their reading, everything else contributes
    itself — so ``話[はな]すを 食[た]べる`` reads ``はなすをたべる``.

    Only the single ASCII space Anki's notation requires *immediately before a
    ruby group* is dropped. Every other space is content: a sentence quoting
    ``「Hello World」`` would otherwise come back as ``HelloWorld``, since
    :func:`romaji.kana_to_romaji` passes Latin text through verbatim. A space
    between two ASCII words is provably not notation.
    """
    out: list[str] = []
    position = 0
    for match in _GROUP.finditer(furigana):
        chunk = furigana[position : match.start()]
        if chunk.endswith(" "):
            chunk = chunk[:-1]
        out.append(chunk)
        out.append(match.group(2))
        position = match.end()
    out.append(furigana[position:])
    return "".join(out)


@dataclass(frozen=True, slots=True)
class FuriganaVerdict:
    """Whether an example's furigana is the dictionary's or the model's.

    ``expected`` and ``found`` are both rendered so a human reading a warning
    can see the whole sentence rather than a list of pairs.
    """

    verified: bool
    expected: str
    found: str
    differences: tuple[str, ...] = ()

    def __bool__(self) -> bool:
        return self.verified


def verify_example_furigana(
    example: ExampleSentence, parse: jpdb.ParseResult
) -> FuriganaVerdict:
    """Check an example's furigana against jpdb's parse of the same sentence.

    The verdict is on the **readings assigned to each kanji run**, in order —
    not on the rendered string. jpdb does not tokenize punctuation, so
    comparing renderings would report a mismatch for a full stop.

    A missing space *does* fail, and should: ``お茶[ちゃ]`` puts ちゃ over both
    characters rather than over 茶, so Anki renders the wrong ruby and
    :func:`furigana_reading` yields ``ちゃ`` — the お is simply gone, and that
    truncated reading is what sentence audio would speak. The space is
    notation, but it is notation that decides which characters a reading
    belongs to.

    A sentence with no kanji has no groups on either side, and verifies.
    """
    expected_pairs = parse_pairs(parse)
    found_pairs = furigana_pairs(example.furigana)
    expected = _render(parse)

    differences: list[str] = []

    # What the furigana says the sentence is, against what the example says it
    # is. Without this only the bracketed groups are checked, so
    # `本[ほん]が 読[よ]む` verifies against the sentence 本を読む — the model
    # rewrote a particle inside the furigana field, and the field that drives
    # sentence audio passes the check built to catch model invention.
    # Normalized on both sides, like the containment check: the furigana janki
    # renders is composed while an example's text is only stripped, so a
    # decomposed dakuten would reject correct furigana — with a message showing
    # two strings that render identically, which is undiagnosable.
    base = normalize_identity_part(furigana_base(example.furigana))
    sentence = normalize_identity_part(
        example.japanese.replace(" ", "").replace("\u3000", "")
    )
    if base and sentence and base != sentence:
        differences.append(
            f"the furigana spells {base}, but the sentence is {sentence}"
        )

    if expected_pairs == found_pairs and not differences:
        return FuriganaVerdict(True, expected, example.furigana)

    for index in range(max(len(expected_pairs), len(found_pairs))):
        theirs = expected_pairs[index] if index < len(expected_pairs) else None
        ours = found_pairs[index] if index < len(found_pairs) else None
        if theirs == ours:
            continue
        if theirs is None:
            differences.append(f"{ours[0]}[{ours[1]}] is not in jpdb's reading")
        elif ours is None:
            differences.append(f"jpdb reads {theirs[0]} as {theirs[1]}; nothing here")
        elif theirs[0] != ours[0]:
            differences.append(
                f"jpdb splits {theirs[0]} where this splits {ours[0]}"
            )
        else:
            differences.append(f"jpdb reads {theirs[0]} as {theirs[1]}, not {ours[1]}")
    return FuriganaVerdict(False, expected, example.furigana, tuple(differences))


def _render(parse: jpdb.ParseResult) -> str:
    """jpdb's own reading of the sentence, in Anki notation, for a human.

    Every token contributes, including the all-kana ones jpdb sends with null
    furigana: a warning that showed only the ruby groups would read as though
    the dictionary had dropped half the sentence.
    """
    segments: list[object] = []
    for token in parse.tokens:
        found = _segments(token.get("furigana"))
        if found:
            segments.extend(found)
            continue
        # A token that resolves to nothing still gets a mark: dropping it is
        # the "the dictionary lost half the sentence" impression this rendering
        # exists to prevent, arriving silently.
        segments.append(token_text(parse, token) or "〈?〉")
    return jpdb.furigana_to_anki(segments)


def regenerate_example_romaji(example: ExampleSentence) -> ExampleSentence:
    """The example with its romaji rebuilt from its furigana.

    Whatever romaji the example arrived with is discarded rather than checked.
    Romaji is a mechanical transliteration of a reading janki already has, so
    there is nothing a model could contribute but an opportunity to be wrong —
    and a wrong romaji is invisible to a learner who is reading it *because*
    they cannot yet read the kana.

    A sentence with no furigana is romanized from its own text, which is right
    when it holds no kanji and refuses to guess when it does: transliterating
    kanji is exactly the invention this function exists to remove.

    **The ASCII space before a ruby group is dropped; everything else stays.**
    That space is Anki's notation, and jpdb segments per kanji, so the verified
    furigana for 日本語 — ``日[にっ] 本[ぽん] 語[ご]`` — romanizes as
    ``nippongo``. Keeping those spaces would give ``ni pon go``: one word split
    into three, with the っ deleted because a sokuon at the end of a run has
    nothing to geminate.

    The rule is positional, not intentional, so a space someone *typed* right
    before a ruby group goes too — ``本を 食[た]べる`` reads ``本をたべる``,
    with the typed space gone. In that position a word space and a notation
    space are indistinguishable in the field. Everywhere else content spacing
    survives into the romaji: quoted Latin keeps its words apart, and so does a
    full-width space between two runs.

    What this does *not* do is insert word boundaries that were not already
    there. Real ones need the parse's tokens, which this function is not given;
    a caller that has one (M4.2) can do better, and :mod:`romaji` is built to
    accept it. The other inherited limit is :mod:`romaji`'s own: は and へ
    romanize as ``ha`` and ``he`` even as particles, because telling a particle
    from a syllable needs segmentation that module deliberately does not have.
    """
    reading = (
        furigana_reading(example.furigana) if example.furigana else example.japanese
    )
    return replace(example, romaji=kana_to_romaji(reading) if reading else "")
