"""Mechanical checks on an example sentence, before anyone believes it.

An AI-written example gets the same distrust an AI-read vocabulary table gets
(DESIGN_V2, "Mechanical QC"). These are the checks a machine can settle without
asking anyone, so that a human review is spent on the things only a human can
judge:

* **Does the sentence actually use the word?** A model asked for an example of
  話す sometimes returns a fine sentence about 言う. The target may appear
  conjugated, so the test is against the code-generated forms from
  :mod:`conjugation` — rules over the expression, not a second guess.
* **Is the furigana the dictionary's, or the model's?** Segmentation is exactly
  what a model invents plausibly and wrongly, and this furigana goes on to
  drive sentence audio. It is checked against jpdb's own parse of the sentence.
* **Is the romaji derived from that furigana?** Model-supplied romaji is
  discarded outright and regenerated by :mod:`romaji`, because romaji is a
  mechanical transliteration and there is no reason to accept a guess at one.

Pure functions, no CLI and no network: the caller supplies the parse.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, replace

from japanese_anki import jpdb
from japanese_anki.conjugation import conjugate, polite_stem
from japanese_anki.identifiers import normalize_identity_part
from japanese_anki.models import ExampleSentence
from japanese_anki.romaji import kana_to_romaji

__all__ = [
    "FuriganaVerdict",
    "example_contains_target",
    "furigana_base",
    "furigana_pairs",
    "furigana_reading",
    "parse_pairs",
    "regenerate_example_romaji",
    "target_forms",
    "token_text",
    "verify_example_furigana",
]

# One bracketed group in Anki furigana notation: the run of characters before
# ``[``, up to a space, and the reading inside the brackets. The space is what
# separates a ruby group from kana in front of it, which is why it terminates
# the text run.
#
# **The ASCII space, and only that.** Anki's own furigana filter separates on
# it alone, so a full-width space — ordinary in Japanese text, and what a model
# may well write — does not end the run there either. Treating it as a
# separator here would verify ``お　茶[ちゃ]`` while Anki renders ちゃ over both
# characters: the same wrong-ruby, truncated-audio failure a missing space
# causes, arriving through a different character.
_GROUP = re.compile(r"([^ \[\]]+)\[([^\[\]]+)\]")


def target_forms(expression: str, verb_group: str = "") -> tuple[str, ...]:
    """Every written form the target may legitimately appear as.

    The dictionary form plus whatever :func:`conjugation.conjugate` derives for
    its class — 話す also shows up as 話した, 話して, 話さない. A word janki has
    no verb class for contributes only its dictionary form, which is the right
    answer rather than a guess: an unconjugatable word simply has to appear as
    written.

    Longest first, so a caller reporting *which* form matched names 話さなかった
    rather than the 話 inside it.
    """
    # Normalized like the sentence it will be searched in. `conjugate`
    # normalizes internally, so the derived forms were already composed — but a
    # word with no verb class contributes only this one, which is most
    # vocabulary, and a decomposed headword would match nothing.
    expression = normalize_identity_part(expression)
    if not expression:
        return ()
    forms = {expression}
    forms.update(
        form for form in conjugate(expression, "", verb_group).values() if form
    )
    # The polite forms too. The style guide asks for examples a beginner can
    # read, and a beginner textbook teaches 〜ます before the plain form — so
    # without these the check would reject almost every good sentence a model
    # writes. Spelled out rather than matching the bare stem, which would let
    # 食べ物 count as an example of 食べる.
    if stem := polite_stem(expression, verb_group):
        forms.update(
            f"{stem}{tail}"
            for tail in ("ます", "ました", "ません", "ませんでした", "まして", "ましょう")
        )
    return tuple(sorted(forms, key=lambda form: (-len(form), form)))


def example_contains_target(
    example: ExampleSentence, expression: str, verb_group: str = ""
) -> bool:
    """Does this example actually use the word it is an example of?

    Checked against the plain sentence rather than the furigana, because the
    furigana carries bracketed readings that would match text no reader sees.
    An example that fails this is rejected outright: it may be a perfectly good
    sentence, but it is not an example of *this* word, and a card whose sentence
    does not contain its own headword teaches the wrong association.
    """
    # Normalized on both sides: `conjugate` returns NFKC forms, while an
    # example's text is only stripped, so a sentence carrying a decomposed
    # dakuten (食べた as た + U+3099 — the combining characters this project's
    # inputs are documented to contain) would never match a composed form. A
    # failed check rejects the example outright, so that miss is a silent drop
    # of a good sentence.
    sentence = normalize_identity_part(example.japanese)
    if not sentence.strip():
        return False
    return any(form in sentence for form in target_forms(expression, verb_group))


def furigana_pairs(furigana: str) -> tuple[tuple[str, str], ...]:
    """The ``(text, reading)`` groups in Anki furigana notation, in order.

    Normalized, like everything else these are compared against: a reading
    written with a decomposed dakuten would otherwise fail against jpdb's
    composed one and report ``jpdb reads 語 as ご, not ご`` — two strings that
    render identically, so the rejection cannot be diagnosed at all.
    """
    return tuple(
        (normalize_identity_part(match.group(1)), normalize_identity_part(match.group(2)))
        for match in _GROUP.finditer(furigana)
    )


def parse_pairs(parse: jpdb.ParseResult) -> tuple[tuple[str, str], ...]:
    """The ``(text, reading)`` groups jpdb's parse of a sentence states."""
    pairs: list[tuple[str, str]] = []
    for token in parse.tokens:
        for segment in _segments(token.get("furigana")):
            if isinstance(segment, str):
                continue
            if len(segment) == 2 and all(isinstance(part, str) for part in segment):
                text, reading = segment
                # The same collapse `jpdb.furigana_to_anki` applies when it
                # writes these fields: a segment that reads as itself carries
                # no ruby, so it is not a group. Without this, furigana janki
                # rendered from a parse could fail verification against that
                # very parse.
                text = normalize_identity_part(text)
                reading = normalize_identity_part(reading)
                if not reading or reading == text:
                    continue
                pairs.append((text, reading))
    return tuple(pairs)


def _segments(value: object) -> list[object]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, list | tuple):
        return list(value)
    return []


#: The only kana that legitimately sit *under* their word's ruby: the honorific
#: prefixes. ``お茶[おちゃ]`` and ``ご飯[ごはん]`` are written this way and are
#: correct. Every other kana-leading run is a group that swallowed the sentence
#: in front of it — including ``は花[はな]``, where the swallowed kana happens to
#: match the reading's first character and a prefix test would wave it through
#: while the は particle vanishes from the reconstructed reading.
_HONORIFIC_PREFIXES = frozenset("おごみ")

#: Kana a ruby group's text run can begin with. Latin and Han are excluded on
#: purpose — ``ＡＴＭ[エーティーエム]`` and ``日[にっ]`` are never spills.
_KANA = re.compile(r"[\u3041-\u309f\u30a0-\u30ff]")


def spilled_furigana_groups(furigana: str) -> tuple[tuple[str, str], ...]:
    """Ruby groups whose reading will be drawn over kana that are not theirs.

    Anki resumes each group's text run where the last one ended, so a group with
    no space before it swallows whatever sits between: ``毎日[まいにち]、妻と
    日本語[にほんご]`` draws にほんご across 妻と日本語, and those particles then
    vanish from :func:`furigana_reading` — which is what the romaji field and
    M5.3's sentence audio are built from.

    Position alone cannot decide this, which is the trap. ``日[にっ]本[ぽん]``
    also abuts with no space and is perfectly correct: there is nothing between
    the groups to spill onto. Nor can "the run starts with kana", which flags
    ``お茶[おちゃ]`` — legitimate whole-word ruby — and following that warning
    yields ``お 茶[おちゃ]``, whose reading is ``おおちゃ``: the check would
    manufacture the defect it exists to catch.

    So it looks at what the run *starts* with, and asks the reading when it has
    to. Three ways a run legitimately begins:

    * a Han character — ``日本語[にほんご]``, the ordinary case;
    * a letter or digit — ``ＡＴＭ[エーティーエム]``, ruby over a loanword;
    * an **honorific prefix** the reading also begins with — ``お茶[おちゃ]``,
      ``ご飯[ごはん]``, which are written as whole-word ruby and are correct.

    Anything else is text the group has swallowed: any other kana
    (``と城崎温泉[きのさきおんせん]``, ``は花[はな]``), an honorific whose reading
    disagrees (``お茶[ちゃ]``), or punctuation (``、妻と日本語[にほんご]``).

    The exemption is a short list rather than "kana the reading starts with",
    which is the tempting generalisation and lets ``は花[はな]`` through — the
    swallowed は matches はな's first character, so a prefix test waves it by
    while は disappears from the reconstructed reading and from the romaji and
    audio built on it. ``お茶[おちゃ]`` and ``は花[はな]`` are structurally
    identical, so only knowing which kana are prefixes separates them.

    **Known gap: a run beginning with a Han character is never flagged.**
    ``毎日[まいにち]妻と日本語[にほんご]`` is a real spill — にほんご is drawn
    across 妻と日本語 — and this returns nothing for it. It cannot be told from
    the legitimate ``日[にっ]本[ぽん]``, or from whole-word ruby over a compound
    that contains kana (``取り引き[とりひき]``), without deciding where the word
    boundary is — which is the segmentation this project refuses to guess at.
    Flagging the class would tell someone to add a space that breaks a correct
    field, which is the harm this function was rewritten to stop causing.

    Returns ``(text run, reading)`` pairs so a message can name them.
    """
    spilled: list[tuple[str, str]] = []
    for match in _GROUP.finditer(furigana):
        raw = match.group(1)
        # Compared normalized, so the verdict does not depend on Unicode
        # composition — a decomposed ご is こ plus a combining mark, and an
        # unnormalized honorific check reports a correct ご飯[ごはん] as a spill.
        # Halfwidth katakana fold into range here too.
        text = normalize_identity_part(raw)
        reading = normalize_identity_part(match.group(2))
        if not reading:
            continue
        # The *first character* comes from the raw run. `normalize_identity_part`
        # strips, and NFKC turns a leading U+3000 into an ASCII space that the
        # strip then removes — so normalizing first deletes exactly the evidence
        # this is looking for. A full-width space where the separator belongs is
        # ordinary in Japanese text (see `_GROUP`), and it does not separate:
        # `furigana_reading` drops only a single ASCII space, so the run before
        # it vanishes from the reading the romaji and audio are built on.
        first = raw[0] if raw else ""
        if not first or first.isspace():
            spilled.append((raw, reading))
        elif _KANA.match(normalize_identity_part(first) or first):
            head = text[0] if text else first
            if not (head in _HONORIFIC_PREFIXES and reading.startswith(head)):
                spilled.append((raw, reading))
        elif not first.isalnum():
            # Punctuation cannot be part of the word the ruby annotates.
            spilled.append((raw, reading))
    # Reported verbatim: a message quoting the NFKC-folded run names a string
    # the record does not contain, so nobody can find what to fix.
    return tuple(spilled)


def repair_spilled_punctuation(furigana: str) -> str:
    """Insert the separator space a group is missing after leading punctuation.

    The one spill whose repair is not a guess. A run beginning with punctuation
    — ``週末[しゅうまつ]、何[なに]するの？`` — has swallowed characters that
    *cannot* belong to the annotated word, and the word plainly starts after
    them, so the space goes between: ``週末[しゅうまつ]、 何[なに]するの？``.
    Nothing about the reading or the segmentation is inferred; only the notation
    separator Anki needs is added, which is why this may run unattended.

    Every other spill is left alone. ``、妻と日本語[にほんご]`` has swallowed a
    noun and a particle as well, and deciding that にほんご annotates 日本語
    rather than 妻と日本語 means choosing where the word begins — a guess about
    segmentation, which this project does not make. Those stay reported by
    :func:`spilled_furigana_groups` for a human.

    Written because `enrich --ai` produced ten of these in one run and the cards
    were built from them: Anki draws なに over ``、何``, and the comma then
    disappears from :func:`furigana_reading`, so it is missing from the romaji
    and from the sentence audio too.
    """

    def separate(match: re.Match[str]) -> str:
        raw, reading = match.group(1), match.group(2)
        leading = 0
        for char in raw:
            # `isalnum` and Han both say "not punctuation" here; the run start
            # rules in `spilled_furigana_groups` are the mirror of this.
            if char.isspace() or char.isalnum() or _KANA.match(char):
                break
            if not unicodedata.category(char).startswith("P"):
                break
            leading += 1
        rest = raw[leading:]
        if not leading or not rest:
            return match.group(0)
        # Only when the remainder is provably the annotated word *alone*, which
        # means no kana anywhere in it. Testing the first character only was not
        # enough: `、妻と日本語[にほんご]` starts with a Han character, so the
        # repair fired and produced `、 妻と日本語[にほんご]` — asserting that
        # にほんご annotates 妻と日本語, which is the segmentation guess this
        # function exists not to make. Worse, it erased the evidence: the run
        # then starts with a Han character, which `spilled_furigana_groups`
        # documents as never flagged, so `janki validate` stopped reporting a
        # defect it had reported before, and 妻と vanished from the reading.
        if any(_KANA.match(char) for char in rest):
            return match.group(0)
        return f"{raw[:leading]} {rest}[{reading}]"

    return _GROUP.sub(separate, furigana)


def stray_furigana_spaces(furigana: str) -> tuple[str, ...]:
    """Spaces that are content rather than notation, with the word after each.

    In a furigana field an ASCII space means one thing: "the next group's text
    run starts here". :func:`furigana_reading` removes a space only when a
    bracketed group follows it, so a space anywhere else survives into the
    reading, into the regenerated romaji, and into the sentence audio — and Anki
    renders it as a gap the plain sentence field does not have.

    ``日本語[にほんご]の ニュースが 少[すこ]し 分[わ]かります。`` has one before
    ニュース, which no group annotates. The card then reads
    ``日本語の ニュースが少し分かります。`` beside an `ExampleJapanese` with no
    gap at all, and the romaji carries the space too.
    """
    stray: list[str] = []
    index = 0
    while index < len(furigana):
        if furigana[index] != " ":
            index += 1
            continue
        # A run, not a character. Two spaces in a row is a plausible typo and
        # exactly what this exists to catch, but reading them one at a time made
        # the first one's "following word" the empty string, which was then
        # reported as "(end of field)" for a space nowhere near the end.
        end = index
        while end < len(furigana) and furigana[end] == " ":
            end += 1
        run, rest = end - index, furigana[end:]
        before = furigana[index - 1] if index else ""
        after = rest[0] if rest else ""
        # Reported only where a space is *provably* not content. Japanese text
        # carries no ASCII spaces, so one between two non-ASCII characters is
        # notation in the wrong place — but `「Hello World」と 言[い]った。` has
        # a space the sentence itself contains, which `furigana_reading` keeps
        # on purpose. Warning about that one sends a reader to delete it, and
        # the romaji becomes HelloWorld.
        provable = run > 1 or (
            bool(before) and bool(after) and not before.isascii() and not after.isascii()
        )
        if provable and (run > 1 or _GROUP.match(rest) is None):
            stray.append(rest.split(" ", 1)[0] or "(end of field)")
        index = end
    return tuple(stray)


def furigana_base(furigana: str) -> str:
    """The sentence a furigana field spells, with every reading removed.

    ``話[はな]すを 食[た]べる`` bases to ``話すを食べる``. This is what the
    furigana claims the sentence *is*, and comparing it with the example's own
    text is what stops a model rewriting the sentence inside the furigana
    field.
    """
    out: list[str] = []
    position = 0
    for match in _GROUP.finditer(furigana):
        out.append(furigana[position : match.start()])
        out.append(match.group(1))
        position = match.end()
    out.append(furigana[position:])
    return "".join(out).replace(" ", "").replace("\u3000", "")


def token_text(parse: jpdb.ParseResult, token: dict) -> str:
    """The written text of one token, furigana or not.

    jpdb sends ``furigana: null`` for an all-kana token — を, と, たべる in the
    committed capture are all null — so a rendering built from furigana alone
    silently drops whole words. The text comes off the dictionary entry the
    token resolves to instead, which is the entry's *dictionary* form: a
    conjugated kana token shows as たべる where the sentence said たべた. That
    is accurate about what jpdb matched, and this text is only ever shown to a
    human beside the sentence itself.
    """
    segments = _segments(token.get("furigana"))
    if segments:
        return "".join(
            segment if isinstance(segment, str) else str(segment[0])
            for segment in segments
        )
    entry = parse.vocabulary_for(token)
    return str(entry.get("spelling") or "") if entry else ""


def furigana_reading(furigana: str) -> str:
    """The kana a whole sentence's Anki furigana spells out.

    Bracketed groups contribute their reading, everything else contributes
    itself — so ``話[はな]すを 食[た]べる`` reads ``はなすをたべる``.

    Only the single ASCII space Anki's notation requires *immediately before a
    ruby group* is dropped. Every other space is content: a sentence quoting
    ``「Hello World」`` would otherwise come back as ``HelloWorld``, since
    :func:`romaji.kana_to_romaji` passes Latin text through verbatim. A space
    between two ASCII words is provably not notation.
    """
    out: list[str] = []
    position = 0
    for match in _GROUP.finditer(furigana):
        chunk = furigana[position : match.start()]
        if chunk.endswith(" "):
            chunk = chunk[:-1]
        out.append(chunk)
        out.append(match.group(2))
        position = match.end()
    out.append(furigana[position:])
    return "".join(out)


@dataclass(frozen=True, slots=True)
class FuriganaVerdict:
    """Whether an example's furigana is the dictionary's or the model's.

    ``expected`` and ``found`` are both rendered so a human reading a warning
    can see the whole sentence rather than a list of pairs.
    """

    verified: bool
    expected: str
    found: str
    differences: tuple[str, ...] = ()

    def __bool__(self) -> bool:
        return self.verified


def _comparable(reading: str) -> str:
    """A reading reduced to the sounds, for comparing two of them.

    jpdb does not tokenize punctuation, so its rendering of 話す。 has no full
    stop while the example's does — comparing them raw reports a mismatch for a
    character neither side disagrees about. Separators go for the same reason.

    Normalized as well, because the two sides come from different places: a
    decomposed dakuten would reject correct furigana, with a message showing two
    strings that render identically, which is undiagnosable.
    """
    text = normalize_identity_part(reading)
    return "".join(
        ch for ch in text if not unicodedata.category(ch).startswith(("P", "Z", "C"))
    )


def verify_example_furigana(
    example: ExampleSentence, parse: jpdb.ParseResult
) -> FuriganaVerdict:
    """Check an example's furigana against jpdb's parse of the same sentence.

    The verdict is on the **readings assigned to each kanji run**, in order —
    not on the rendered string. jpdb does not tokenize punctuation, so
    comparing renderings would report a mismatch for a full stop.

    A missing space *does* fail, and should: ``お茶[ちゃ]`` puts ちゃ over both
    characters rather than over 茶, so Anki renders the wrong ruby and
    :func:`furigana_reading` yields ``ちゃ`` — the お is simply gone, and that
    truncated reading is what sentence audio would speak. The space is
    notation, but it is notation that decides which characters a reading
    belongs to.

    **Granularity is not disagreement.** jpdb returns furigana per *character* —
    週[しゅう] 末[まつ] — while an example is written per *word*, 週末[しゅうまつ],
    which is how Anki decks are read and what belongs on a card. Comparing the
    group sequences pairwise therefore failed on every multi-kanji compound:
    仕事, 漢字, 意味, 明日, 毎日 all "differed" while saying exactly the same
    thing. Measured against a real jpdb import, that flagged 12 of 17 correct
    examples and passed only the sentences whose words happened to be single
    kanji — so the check was mostly reporting its own segmentation, and the
    audio it suppressed was audio of correct sentences.

    Comparing the *joined group texts* fixed those and broke a worse set: jpdb
    does not tokenize the leading kana of お茶, so its ruby covers 茶 while a
    card's covers お茶. The correct ``お茶[おちゃ]`` failed while the wrong
    ``お 茶[ちゃ]`` — which reads おおちゃ — passed. That is the defect
    :func:`spilled_furigana_groups` names as the one a naive fix manufactures,
    and it suppressed sentence audio permanently: ``janki audio`` skips a
    flagged example and ``recheck_furigana`` can only clear what this verifies.

    So the verdict is on **what the sentence sounds like**: the kana
    :func:`furigana_reading` spells out of the example, against the kana it
    spells out of jpdb's own rendering. That is what the consumers depend on —
    sentence audio speaks it, romaji is transliterated from it — and it is blind
    to both granularity and ruby extent while still catching:

    * a wrong reading — jpdb reads 日本語 as にっぽんご where an example says
      にほんご; and
    * the ``お茶[ちゃ]`` spill, which reads ちゃ where jpdb reads おちゃ: the お
      is simply gone, and that truncated reading is what would be spoken.

    A sentence with no kanji has no groups on either side, and verifies.

    **Known limitation.** jpdb sends some tokens with ``furigana: null`` and
    :func:`_render` falls back to the vocabulary entry, which is the *dictionary
    form* — so できます renders as できる and a sentence using it is flagged for a
    difference nobody made. Measured on a real 20-record import this cost one
    example out of twenty, and that one also carried a genuine にっぽんご/にほんご
    disagreement, so it was going to be flagged anyway. Closing it means asking
    jpdb's parse for ``position``/``length`` and slicing the surface form out of
    the sentence, which changes what every caller of ``_render`` sees; it is
    worth doing when a flagged-but-correct example costs more than a re-check.
    """
    expected = _render(parse)

    expected_reading = _comparable(furigana_reading(expected))
    # Falling back to the sentence when there is no furigana field at all: an
    # all-kana sentence needs none, and its reading *is* its text. A sentence
    # with kanji still fails, because the kanji pass through unread — 話す
    # yields 話す, not はなす.
    found_reading = _comparable(furigana_reading(example.furigana or example.japanese))

    differences: list[str] = []

    # What the furigana says the sentence is, against what the example says it
    # is. Without this only the bracketed groups are checked, so
    # `本[ほん]が 読[よ]む` verifies against the sentence 本を読む — the model
    # rewrote a particle inside the furigana field, and the field that drives
    # sentence audio passes the check built to catch model invention.
    # Normalized on both sides, like the containment check: the furigana janki
    # renders is composed while an example's text is only stripped, so a
    # decomposed dakuten would reject correct furigana — with a message showing
    # two strings that render identically, which is undiagnosable.
    base = normalize_identity_part(furigana_base(example.furigana))
    sentence = normalize_identity_part(
        example.japanese.replace(" ", "").replace("\u3000", "")
    )
    if base and sentence and base != sentence:
        differences.append(
            f"the furigana spells {base}, but the sentence is {sentence}"
        )

    if expected_reading == found_reading and not differences:
        return FuriganaVerdict(True, expected, example.furigana)

    if expected_reading != found_reading:
        differences.append(
            f"jpdb reads this as {expected_reading or '(nothing)'}; the furigana "
            f"reads {found_reading or '(nothing)'}"
        )

    # No per-group differences appended: since the verdict stopped depending on
    # grouping, "jpdb splits 来 where this splits 来週" describes something that
    # is not a failure, and printing it beside the real reason invites the
    # reader to fix the thing that was already fine.
    return FuriganaVerdict(False, expected, example.furigana, tuple(differences))


def _render(parse: jpdb.ParseResult) -> str:
    """jpdb's own reading of the sentence, in Anki notation, for a human.

    Every token contributes, including the all-kana ones jpdb sends with null
    furigana: a warning that showed only the ruby groups would read as though
    the dictionary had dropped half the sentence.
    """
    segments: list[object] = []
    for token in parse.tokens:
        found = _segments(token.get("furigana"))
        if found:
            segments.extend(found)
            continue
        # A token that resolves to nothing still gets a mark: dropping it is
        # the "the dictionary lost half the sentence" impression this rendering
        # exists to prevent, arriving silently.
        segments.append(token_text(parse, token) or "〈?〉")
    return jpdb.furigana_to_anki(segments)


def regenerate_example_romaji(example: ExampleSentence) -> ExampleSentence:
    """The example with its romaji rebuilt from its furigana.

    Whatever romaji the example arrived with is discarded rather than checked.
    Romaji is a mechanical transliteration of a reading janki already has, so
    there is nothing a model could contribute but an opportunity to be wrong —
    and a wrong romaji is invisible to a learner who is reading it *because*
    they cannot yet read the kana.

    A sentence with no furigana is romanized from its own text, which is right
    when it holds no kanji and refuses to guess when it does: transliterating
    kanji is exactly the invention this function exists to remove.

    **The ASCII space before a ruby group is dropped; everything else stays.**
    That space is Anki's notation, and jpdb segments per kanji, so the verified
    furigana for 日本語 — ``日[にっ] 本[ぽん] 語[ご]`` — romanizes as
    ``nippongo``. Keeping those spaces would give ``ni pon go``: one word split
    into three, with the っ deleted because a sokuon at the end of a run has
    nothing to geminate.

    The rule is positional, not intentional, so a space someone *typed* right
    before a ruby group goes too — ``本を 食[た]べる`` reads ``本をたべる``,
    with the typed space gone. In that position a word space and a notation
    space are indistinguishable in the field. Everywhere else content spacing
    survives into the romaji: quoted Latin keeps its words apart, and so does a
    full-width space between two runs.

    What this does *not* do is insert word boundaries that were not already
    there. Real ones need the parse's tokens, which this function is not given;
    a caller that has one (M4.2) can do better, and :mod:`romaji` is built to
    accept it. The other inherited limit is :mod:`romaji`'s own: は and へ
    romanize as ``ha`` and ``he`` even as particles, because telling a particle
    from a syllable needs segmentation that module deliberately does not have.
    """
    reading = (
        furigana_reading(example.furigana) if example.furigana else example.japanese
    )
    return replace(example, romaji=kana_to_romaji(reading) if reading else "")
